action updated

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,8 +1,8 @@
 name: Building
-on: 
-  push:
-    tags:
-      - "v*.*.*" # Este on solo se ejecuta cuando hay etiqueta que cumpla el patrón
+on: [push]
+#  push:
+#    tags:
+#      - "v*.*.*" # Este on solo se ejecuta cuando hay etiqueta que cumpla el patrón
 jobs:
   building:
     runs-on: ubuntu-latest
@@ -16,9 +16,19 @@ jobs:
       - name: install dependencies
         run: poetry install
       - name: Testing
-        run: poetry run pytest
+        run: poetry run pytest --junitxml=jest-junit.xml
+        uses: dorny/test-reporter@v1
+        
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results
+          path: jest-junit.xml
+          reporter: jest-junit              # Format of test results
+
+
       - run: poetry build # Ejecuta un comando de consola en el repo
-      - name: Publication
+      - name: Publish to GH Releases
+        if: startsWith(github.ref, 'refs/tags/v') 
         uses: softprops/action-gh-release@v1
         with:
           files: ${{ github.workspace }}/dist/*
