action updated

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,18 +16,14 @@ jobs:
       - name: install dependencies
         run: poetry install
       - name: Testing
-        run: poetry run pytest --junitxml=java-junit.xml
-        
-
+        run: poetry run pytest --junitxml=jest-junit.xml
       - name: Test Report
-        uses: dorny/test-reporter@v1 
-        if: success() || failure()        # run this step even if previous step failed
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          name: test-results
-          path: java-junit.xml
-          reporter: java-junit              # Format of test results
-
-
+          name: Test            # Name of the check run which will be created
+          path: jest-junit.xml    # Path to test results
+          reporter: java-junit        # Format of test results
       - run: poetry build # Ejecuta un comando de consola en el repo
       - name: Publish to GH Releases
         if: startsWith(github.ref, 'refs/tags/v') 
